[package]
name = "charliey2/profileservice"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["loleris"]
description = "Forked version of ProfileService for use with Wally."
realm = "shared"
licence = "Apache-2.0"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
]

[dependencies]
